"""What "the right code is on this board" means, as a single comparable string.

A controller's expected firmware is a function of four things: which routines
it must provide, which pins those routines drive, the protocol it speaks, and
the source it was built from. Hash all four and you get a value the board can
report back, so preflight can answer "is this board already correct?" without
reflashing it to find out.

The fingerprint is baked into the build via a generated identity header, so it
works with the current hand-written sketches. When firmware generation lands,
the same fingerprint covers the generated sources instead - the wire format
does not change.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from pathlib import Path

from app.controllers.simulation import IDENTITY_PROTOCOL_VERSION

# The header the fingerprint is written into. Excluded from the source hash for
# the obvious reason: including it would make the hash depend on itself.
GENERATED_IDENTITY_FILENAME = "generated_identity.h"

FINGERPRINT_LENGTH = 16

_HASHED_SOURCE_SUFFIXES = {".ino", ".h", ".hpp", ".c", ".cpp"}


@dataclass(frozen=True)
class PinAssignment:
    device_id: str
    signal: str
    gpio: str


@dataclass
class FirmwareBundle:
    """Everything that decides what should be running on one controller."""

    controller_id: str
    routines: list[str] = field(default_factory=list)
    pins: list[PinAssignment] = field(default_factory=list)
    protocol: int = IDENTITY_PROTOCOL_VERSION
    source_hashes: dict[str, str] = field(default_factory=dict)
    # Human-readable label, carried so a board can say "I am the Z axis
    # controller" and not just an opaque id. Deliberately NOT part of the
    # fingerprint: renaming a controller in the Hardware Map must not make
    # every board look like it needs reflashing.
    controller_name: str = ""

    def canonical_payload(self) -> dict:
        """Order-independent description. Two builds that differ only in the
        order things were collected must produce the same fingerprint."""
        pins_by_device: dict[str, dict[str, str]] = {}
        for pin in self.pins:
            pins_by_device.setdefault(pin.device_id, {})[pin.signal] = str(pin.gpio)

        return {
            "controller_id": self.controller_id,
            "protocol": self.protocol,
            "routines": sorted(set(self.routines)),
            "pins": {
                device_id: dict(sorted(signals.items()))
                for device_id, signals in sorted(pins_by_device.items())
            },
            "sources": dict(sorted(self.source_hashes.items())),
        }

    def fingerprint(self) -> str:
        canonical = json.dumps(self.canonical_payload(), sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:FINGERPRINT_LENGTH]


def hash_firmware_sources(firmware_dir: Path) -> dict[str, str]:
    """Hash every compiled source in a firmware directory.

    Paths are recorded relative to the directory so that moving a workspace
    does not change the fingerprint, and the generated identity header is
    skipped so the hash is not self-referential.
    """
    if not firmware_dir.exists():
        return {}

    hashes: dict[str, str] = {}
    for path in sorted(firmware_dir.rglob("*")):
        if not path.is_file():
            continue
        if path.name == GENERATED_IDENTITY_FILENAME:
            continue
        if path.suffix.lower() not in _HASHED_SOURCE_SUFFIXES:
            continue

        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        hashes[path.relative_to(firmware_dir).as_posix()] = digest

    return hashes


def _c_string(value: str) -> str:
    """Escape a value for embedding in a C string literal.

    Controller ids and names come from the Hardware Map, which a user edits
    freely - a stray quote or backslash would otherwise emit a header that
    does not compile, turning a typo into a failed flash.
    """
    return (value or "").replace("\\", "\\\\").replace('"', '\\"')


def render_identity_header(bundle: FirmwareBundle) -> str:
    """The header the sketch includes so it can answer `ID?`.

    Only identity goes in here. Pin definitions stay wherever the sketch keeps
    them today; moving those is the firmware-generation pass, not this one.
    """
    routines = sorted(set(bundle.routines))
    routine_list = ", ".join(f'"{routine}"' for routine in routines) or '""'

    return "\n".join(
        [
            "// Generated by the backend at flash time. Do not edit.",
            "//",
            "// Lets the controller answer ID? with who it is and what was built",
            "// into it, so a run can verify the right firmware is present",
            "// instead of reflashing every board before every workflow.",
            "#pragma once",
            "",
            f'#define ROBOT_CONTROLLER_ID "{_c_string(bundle.controller_id)}"',
            f'#define ROBOT_CONTROLLER_NAME "{_c_string(bundle.controller_name)}"',
            f'#define ROBOT_FIRMWARE_FINGERPRINT "{bundle.fingerprint()}"',
            f"#define ROBOT_IDENTITY_PROTOCOL {bundle.protocol}",
            f"#define ROBOT_ROUTINE_COUNT {len(routines)}",
            f"static const char* ROBOT_ROUTINES[] = {{{routine_list}}};",
            "",
        ]
    )


@dataclass(frozen=True)
class ControllerIdentity:
    """What a board reported when asked."""

    controller_id: str | None
    fingerprint: str | None
    protocol: int | None
    routines: tuple[str, ...]
    raw_reply: str
    # Human-readable label the board reports. Absent on firmware built before
    # names existed, which is not an error - it just cannot introduce itself.
    name: str | None = None

    @classmethod
    def parse(cls, reply: str) -> "ControllerIdentity | None":
        """Parse an `ID?` reply. Returns None when it is not an identity reply.

        Tolerant on purpose: a board running pre-handshake firmware answers
        with whatever it does for unknown commands, and that has to read as
        "no identity", not as a crash.
        """
        text = (reply or "").strip()
        if not text.startswith("{"):
            return None

        try:
            payload = json.loads(text)
        except json.JSONDecodeError:
            return None

        if not isinstance(payload, dict) or "controller_id" not in payload:
            return None

        routines = payload.get("routines") or []
        return cls(
            controller_id=payload.get("controller_id") or None,
            name=payload.get("name") or None,
            fingerprint=payload.get("fingerprint") or None,
            protocol=int(payload["protocol"]) if isinstance(payload.get("protocol"), int) else None,
            routines=tuple(str(routine) for routine in routines) if isinstance(routines, list) else (),
            raw_reply=text,
        )
